### ISSUE TITLE
Running into Error(500)

### ISSUE THREAD

**Issue by jalotra** [abhishekkrthakur/colabcode#77]
error vscode [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character
error vscode Error: [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character
    at /usr/lib/code-server/lib/vscode/out/vs/server/entry.js:124:875
    at new u (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:125:166)
    at new d (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:126:773)
    at Function.from (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:126:213)
    at n (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:546:1003)
    at t.Vscode.initialize (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:547:174)
    at async process.<anonymous> (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:553:517)
[2021-04-09T19:50:18.382Z] error VS Code exited unexpectedly with code 1

**Comment by misalraj** [comment]
What do you mean? can you give an example? @jalotra

**Comment by jalotra** [comment]
I don't know exactly, I think there was some bug in the way codeserver handles request, but not sure.

**Comment by misalraj** [comment]
It should be fine. Anyway, we will update the code-server version.
